<a href="https://colab.research.google.com/github/ruppikha/AURORA/blob/main/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def f1():
  print("In Function1")
  list = []
  for i in range(4,20):
    if i%2==0:
      print('* '*i)
      l.append(i)
  return l


l = []
l = f1()
print(l)

5
5.5
Hello
In Function1
* * * * 
* * * * * * 
* * * * * * * * 
* * * * * * * * * * 
* * * * * * * * * * * * 
* * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * 
[4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
print("Hello World") #Printing
print("Welcome") 

Hello World
Welcome


Indentation: Blocks of code are defined using indentation in Python
\
Alternative to { } in C

In [ ]:
print("A")
  print("C") #Indentation error

IndentationError: ignored

**Variables**

In [ ]:
a = 'Hello' #No need to mention the data type
b = 9
c = 4.5
d,e,f = "World",1,3.5 
g = True
h = b<c
print(a + " World") 
print(b+7) 
print(a,b,c)
print(d,e,f)  
print(g,h)

Hello World
16
Hello 9 4.5
World 1 3.5
True False


**Conditional Statements**

In [ ]:
if b>c:
  print("Yes") #Observe: Indentation to show a block of code
else:
  print("No")
print("A")

Yes
A


In [ ]:
a=15
if a>20:
  print("A is greater than 20")
elif a>10 and a<20: # elif == else if
  print("A is greater than 10 and less than 20")
else:
  print("A is less than 10")

**Taking Inputs**

By default input is taken as a string. It can be converted to other data types by typecasting it. 

In [ ]:
x = input("Enter a message: ")
print(x)

y = int(input("Enter a number: "))
print(y)

z = float(input("Enter a decimal number: "))
print(z)

Enter a message: Hello
Hello
Enter a number: 5
5
Enter a decimal number: 4.5
4.5


**Relational Operators:** 
< , > , == , >= , <= , !=
\
**Logical Operators:** 
and , or , not

**Looping** - for and while
\
Run through a block of code given number of times

In [ ]:
# range([start,]end[,step]) start and step are optional arguments
for x in range(11): #0 to end-1
  print(x, end = "-")
y=0
print()
while(y<11):
  print(y,end = "-")
  y+=1
print()
print()
for i in range(1,10): #start to end-1
  print(i ,end = " ")

0-1-2-3-4-5-6-7-8-9-10-
0-1-2-3-4-5-6-7-8-9-10-

1 2 3 4 5 6 7 8 9 

In [ ]:
for i in range(1,10,2): # Here, Step = 2. After every iteration, i = i + 2
  print(i , end = " ")
print()
y = 1
while(y<11):
  print(y,end = " ")
  y+=2
#For loops and while loops can be used interchangably

1 3 5 7 9 
1 3 5 7 9 

In [ ]:
for i in [11,12,13,14]:
  print(i,end = "--")

11--12--13--14--

Q. Attempt to display the pattern:

1

2 3 

4 5 6

7 8 9 10

**Functions**
\
A function is a block of code which only runs when it is called. Helps in reusability of codes
\
No need to mention data type of parameters and the return type

In [ ]:
def sample(a,b):
  return a+b

x = sample(4,5) #Returned value can be stored in a variable
y = 6
z = x + y
print(x,z)


# Returned value can be printed directly
print(sample(3.5,7.2))
print(sample("Hello"," World"))



9 15
10.7
Hello World


# **PROGRESS CHECK**

In [ ]:
def factorial(n):
    result = n
    start = n
    n -= 1
    while n>0: 
        result *= n 
                 #Decrement statemnt
    return        #what should be returned?
  


Q. Write a Python function to find the Max of three numbers.

**String Basics** 

In [ ]:
print("Hello")
print('Hello')
#Both prints "Hello"


a = "AURORA!"
print(a[1])
#counts from 0


for x in "AURORA":
  print(x , end = " ")
#prints AURORA

print()

a = "Hello, World!"
print(len(a))
#prints the length of a

txt = "Hello World"
if "Hello" in txt:
  print("Yes, 'Hello' is present.")


a = "Hello, World!"
print(a.upper())

a = "Hello, World!"
print(a.lower())



Hello
Hello
U
A U R O R A 
13
Yes, 'Hello' is present.
HELLO, WORLD!
hello, world!


**String Slicing**

In [ ]:
b = "Hello, World!"
print(b[2:5]) #(x,y-1)
print(b[2:])
print(b[:5])
print(b[-5:])
#b[1] = 'i'
print(b[-1*len(b):])

llo
llo, World!
Hello
orld!
Hello, World!


**String Formatting**

In [ ]:
age = 26
txt = "I am {} years old"
print(txt.format(age)) 


quantity = 3
item = "chocolate"
price = 30.25
myorder = "I want {} pieces of {} for {} dollars."
print(myorder.format(quantity, item, price))

I am 26 years old
I want 3 pieces of chocolate for 30.25 dollars.


**Lists** 

List is a collection which is ordered and mutable. Allows duplicate members.

In [ ]:
thislist = list(("apple", "banana", "cherry")) # note the double round-brackets
print(thislist)
print()


thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5])
print(thislist[-5:])
print()

#Changing elements in the list:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)
print()

thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "watermelon")
print(thislist)
del thislist[-1:]
print(thislist)
print()

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)
#adds the contents into a new list

['apple', 'banana', 'cherry']

['cherry', 'orange', 'kiwi']
['cherry', 'orange', 'kiwi', 'melon', 'mango']

['apple', 'blackcurrant', 'watermelon', 'orange', 'kiwi', 'mango']

['apple', 'banana', 'watermelon', 'cherry']
['apple', 'banana', 'watermelon']

['apple', 'banana', 'mango']


**LIST METHODS**

list.append(elem) -- adds a single element to the end of the list. Common error: does not return the new list, just modifies the original.

list.insert(index, elem) -- inserts the element at the given index, shifting elements to the right.

list.extend(list2) -- adds the elements in list2 to the end of the list. Using + or += on a list is similar to using extend().

list.index(elem) -- searches for the given element from the start of the list and returns its index. Throws a ValueError if the element does not appear 

list.remove(elem) -- searches for the first instance of the given element and removes it (throws ValueError if not present)

list.sort() -- sorts the list in place (does not return it). 

list.reverse() -- reverses the list in place (does not return it)

list.pop(index) -- removes and returns the element at the given index. Returns the rightmost element if index is omitted (roughly the opposite of append()).

**Dictionaries**
\
Key-Value pairs
\
Keys are immutable but values are mutable
\
Unordered collections
\
Heterogenous values can be stored


In [ ]:
#Dictionary items are ordered, changeable, have different datatypes and does not allow duplicates.

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

x = thisdict.get("model")
print(x,"\n")

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["color"] = "red"
print(thisdict)
#adds a key to the dictionary

if "model" in thisdict:
  print("Yes, 'model' is one of the keys in the thisdict dictionary\n")

del thisdict['year']
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Mustang 

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}
Yes, 'model' is one of the keys in the thisdict dictionary

{'brand': 'Ford', 'model': 'Mustang', 'color': 'red'}


**DICTIONARY METHODS**

dict.keys() - Returns a list of the keys

dict.values() - Returns a list of the values

dict.items() - Returns a tuple containing the (key,value) pairs


In [ ]:
dict = {}
dict['a'] = 'alpha'
dict['g'] = 'gamma'
dict['o'] = 'omega'

for key in dict: print(key, end = " ") #Will return the same as - for key in dict.keys()

print()
for val in dict.values(): print(val,end = " ")

print()
for k,v in dict.items():
  print(k,"->",v)

dict['b'] = "beta"
print(dict)
print(sorted(dict)) #List of keys in sorted order. Done in place
del dict['o']
print(dict)

a g o 
alpha gamma omega 
a -> alpha
g -> gamma
o -> omega
{'a': 'alpha', 'g': 'gamma', 'o': 'omega', 'b': 'beta'}
['a', 'b', 'g', 'o']
{'a': 'alpha', 'g': 'gamma', 'b': 'beta'}


Other data collection structures: Tuples(Immutable,ordered,heterogenous) and Sets(Mutable,Unordered,Homogenous)
\
tuple_ex = (1,2,3)
\
set_ex = {1,2,3}

**NUMPY**

In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3, 4, 5])
print('x = ', x) 
print('x has dimensions:', x.shape) 
print('The elements in x are of type:', x.dtype)

print()
# Create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print('Y has dimensions:', Y.shape) 
print('Y has a total of', Y.size, 'elements') 
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 

x =  [1 2 3 4 5]
x has dimensions: (5,)
The elements in x are of type: int64

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [ ]:
print(x+3)
print(x*5) 
print(x-1)
print(x**2) #Performs the mathematical operations on elements of the ndarray

[4 5 6 7 8]
[ 5 10 15 20 25]
[0 1 2 3 4]
[ 1  4  9 16 25]


In [ ]:
l1 = [1,2,3,4]
print(l1*2) #Doubles the list and returns the combined list

[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
X = np.zeros((3,4))
Y = np.ones((5,6))
Z = np.full((4,3), 5)
print(X,"\n",Y,"\n",Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 
 [[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
x = np.arange(10)
y = np.arange(10,20)
print(x,y)

[0 1 2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18 19]


In [ ]:
X = np.arange(20).reshape(4, 5)
print(X,"\n")

X[0,0] = 20
print(X,"\n")

Z = X[1:4,2:5]
print(Z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[20  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
x = np.array([1, 2, 3, 4, 5])
x = np.append(x, 6)
x = np.append(x, [7,8])
print("Before deleting: ", x)
x = np.delete(x, [0,4]) #Deletes the 1st(0th indes) and 5th(4th index) element from x
print("After deleting: ", x)
print()

Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
Y = np.append(Y, [[10,11,12]], axis=0)
print("Before deleting:\n",Y)
Y = np.delete(Y, 0, axis=0) #Deletes the first row(axis = 0)
Y = np.delete(Y, [0,2], axis=1) #Deletes the first and the 3rd columns(axis = 1)
print("After deleting:\n",Y)

Before deleting:  [1 2 3 4 5 6 7 8]
After deleting:  [2 3 4 6 7 8]

Before deleting:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
After deleting:
 [[ 5]
 [ 8]
 [11]]


**Other numpy methods:**
\
np.insert(x,2,[3,4]) - Will insert the list at index 2 in x
\
np.vstack((x,y)) - Stack the 2 ndarrays vertically. Number of columns should match
\
np.hstack((x,y)) - Stack the 2 arrays horizontally. Number of rows should match
\
Z = np.copy(X[1:4,2:5]) - Creates a copy of the passed ndarray
\
np.sort(x)

**Math Functions**

1) np.add(X,Y)
\
2) np.subtract(X,Y)
\
3) np.multiply(X,Y)
\
4) np.divide(X,Y)
\
5) np.exp(x)
\
6) np.sqrt(x)
\
7) np.power(x,2)

**Statistical Functions**\
min(), max(), sum(), mean(), median(), std()
\
ndarray-name.min() (or) ndarray-name.max()

**PANDAS**

In [ ]:
import pandas as pd 

Series: 1D data, can hold heterogenous values & indexes are labelled

In [ ]:
groceries = pd.Series(data = [30, 6, 'Yes', 'No'], index = ['eggs', 'apples', 'milk', 'bread'])
print(groceries)
print()
#print(groceries.shape)
#print(groceries.ndim)
#print(groceries.size)
#print(groceries.values)
#print(groceries.index)

eggs       30
apples      6
milk      Yes
bread      No
dtype: object



In [ ]:
print(groceries["eggs"])
print(groceries[["milk","bread"]])

30
milk     Yes
bread     No
dtype: object


In [ ]:
groceries.drop("apples")
print(groceries)
groceries.drop("apples", inplace = True)

eggs       30
apples      6
milk      Yes
bread      No
dtype: object
eggs      30
milk     Yes
bread     No
dtype: object


In [ ]:
print(groceries)

eggs       30
apples      6
milk      Yes
bread      No
dtype: object


DataFrames: 2D data, Rows and columns are labelled

In [ ]:
items = {'Bob' : [245, 25, 55,40,30], 'Alice' : [40, 110, 450, 45,10]}
df = pd.DataFrame(items)
print(df,"\n")
df.index = ['book','watch','pants','shirts','bike']
df["Bob"]["book"] = 30
print(df,"\n")

   Bob  Alice
0  245     40
1   25    110
2   55    450
3   40     45
4   30     10 

        Bob  Alice
book     30     40
watch    25    110
pants    55    450
shirts   40     45
bike     30     10 



In [ ]:
user_1 = pd.Series(data = [3.2, np.nan ,2.5])
user_2 = pd.Series(data = [5., 1.3, 4.0, 3.8])
user_3 = pd.Series(data = [2.0, 2.3, np.nan, 4])
user_4 = pd.Series(data = [4, 3.5, 4, 5, 4.2])

udict = {"U1":user_1,"U2":user_2,"U3":user_3,"U4":user_4}
df1 = pd.DataFrame(udict,columns = ["U1","U2","U3","U4"])
df1

U1   U2   U3   U4
0  3.2  5.0  2.0  4.0
1  NaN  1.3  2.3  3.5
2  2.5  4.0  NaN  4.0
3  NaN  3.8  4.0  5.0
4  NaN  NaN  NaN  4.2

In [ ]:
df2 = df1.fillna(df1.median())
df3 = df1.fillna(0)
print(df2,"\n",df3)

     U1   U2   U3   U4
0  3.20  5.0  2.0  4.0
1  2.85  1.3  2.3  3.5
2  2.50  4.0  2.3  4.0
3  2.85  3.8  4.0  5.0
4  2.85  3.9  2.3  4.2 
     U1   U2   U3   U4
0  3.2  5.0  2.0  4.0
1  0.0  1.3  2.3  3.5
2  2.5  4.0  0.0  4.0
3  0.0  3.8  4.0  5.0
4  0.0  0.0  0.0  4.2


In [ ]:
print(df2.sum(),"\n")
print(df2.sum(axis=1),"\n")
print(df2.head(3))
print(df2.tail(2))
df2.describe()
print()
df2.max() #Max value in each column
df2.info()
df2.memory_usage()

U1    14.25
U2    18.00
U3    12.90
U4    20.70
dtype: float64 

0    14.20
1     9.95
2    12.80
3    15.65
4    13.25
dtype: float64 

     U1   U2   U3   U4
0  3.20  5.0  2.0  4.0
1  2.85  1.3  2.3  3.5
2  2.50  4.0  2.3  4.0
     U1   U2   U3   U4
3  2.85  3.8  4.0  5.0
4  2.85  3.9  2.3  4.2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   U1      5 non-null      float64
 1   U2      5 non-null      float64
 2   U3      5 non-null      float64
 3   U4      5 non-null      float64
dtypes: float64(4)
memory usage: 288.0 bytes


Index    128
U1        40
U2        40
U3        40
U4        40
dtype: int64

In [ ]:
df = pd.read_csv('Book1.csv')
print(df)

   Sno Initial
0    1       A
1    2       B
2    3       C
3    4       D
4    5       E
5    6       F


In [ ]:
df2.to_csv("Book3.csv",index = False)